### ISSUE TITLE
tsi-indent-line: Symbol’s value as variable is void: node-at-point

### ISSUE THREAD

**Issue by root0x** [orzechowskid/tsi.el#31]
I have added the tsi and tsx-mode packages to my emacs config but anytime I try and tab when tsi-typescript-mode is enabled I get the error `tsi-indent-line: Symbol’s value as variable is void: node-at-point`. If i disable tsi-typescript-mode then I do not recieve the error but just adds 1 tab not indents the line to where It should be. I am using emacs-plus@28.1 on OS X Monteray on a m1 macbook pro. My emacs config contains

```
(use-package lsp-mode
  :init
  ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
  (setq lsp-keymap-prefix "C-c l")
  :config
  (add-to-list 'lsp-file-watch-ignored-directories "[/\\\\]\\node_modules\\'")
  (add-to-list 'lsp-file-watch-ignored-directories "[/\\\\]\\vendor\\'")
  :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
         (typescript-mode . lsp)
	 (php-mode . lsp)
	 (vue-mode . lsp)
         ;; if you want which-key integration
         (lsp-mode . lsp-enable-which-key-integration))
  :bind (("s-<down>" . lsp-find-definition))
  :commands lsp)

(use-package lsp-ui :commands lsp-ui-mode)

(use-package lsp-ivy
  :commands lsp-ivy-workspace-symbol)
(use-package lsp-treemacs
  :commands lsp-treemacs-errors-list
  :config
  (lsp-treemacs-sync-mode 1))

(with-eval-after-load 'treemacs
  (define-key treemacs-mode-map [mouse-1] #'treemacs-single-click-expand-action))



(use-package typescript-mode
  :mode "\\.ts\\'"
  :hook (typescript-mode . lsp-deferred)
  :config
  (setq typescript-indent-level 4)
  )

(use-package tsi
  :straight (tsi
	     :type git
       	     :host github
	     :repo "orzechowskid/tsi.el")
  )


(use-package tsx-mode
  :mode "\\.tsx\\'"
  :straight (tsx-mode
	     :type git
	     :host github
	     :repo "orzechowskid/tsx-mode.el")  )

(with-eval-after-load 'tree-sitter-langs
  (tree-sitter-require 'tsx)
  (add-to-list 'tree-sitter-major-mode-language-alist '(typescript-mode . tsx)))
```

A link to my full config is [https://github.com/root0x/Emacs](https://github.com/root0x/Emacs)

And example of the file I was testing with is

```import { useQuery } from 'react-query';
import { Link } from 'react-router-dom';
import { useState } from 'react';

const Contact = () =>
{
    const { data } = useQuery('/contact/2');

    return (
        <>
	<div>goodbye universe</div>
            <Link to="/test">Link</Link>
        </>
    );
};

export default Contact;
```

Thanks for creating this package and tsx-mode I am really looking forward to playing around with them so I can supercharge my emacs setup. Even with the tabs not working as intended this is much better thab using web-mode.

**Comment by orzechowskid** [comment]
I agree that this is probably a dupe, but I'm curious as to why it's happened twice now and what I can do differently with this repository to prevent it from happening in the future.  I've never experienced this problem so I'm not sure how to go about diagnosing and addressing it.

**Comment by root0x** [comment]
Hi, I have removed the eln-cache folder in ~/.emacs.d/ the elpa packages and everything else I could think of in that folder but i'm unfortunately still getting this error. I'm running emacs-plus 28.1 without native comp if that makes any difference. Would there be any information that I could send you that could help?

**Comment by orzechowskid** [comment]
perhaps try deleting your .eln files, then running `straight-pull-all` followed by `straight-rebuild-all`. that should get you up-to-date source and binary files.  I'm a little confused though since I thought .eln files were outputs of emacs' native compilation process, but you say you're running emacs-plus _without_ native comp?

**Comment by orzechowskid** [comment]
> Would there be any information that I could send you that could help?

I suppose you could also try updating your straight.el recipe for tsi.el to use the `chore/update-deprecated-fns` branch.  the value for `node-at-point` is set by calling a tree-sitter function which has since been deprecated.  that branch removes calls to the deprecated function in favor of a more recently added function.

if that still doesn't work, then maybe `(setq debug-on-error t)` and trigger the problem and paste the stack trace here.

**Comment by root0x** [comment]
Thanks for all the help. I tried the new branch and rebuilding the package but that unfortunately didnt work. What i did do is recompile emacs with native comp and that has made the packages work without errors. Is native comp a requirement for these packges?

**Comment by stevemolitor** [comment]
I mentioned this in the other issue, but if `node-at-point` returned `void` instead of `nil` in certain setups it could explain this issue.

From the error It looks like it's complaining that node-at-point is void around [here](https://github.com/orzechowskid/tsi.el/blob/main/tsi-typescript.el#L376-L379):

```elisp
  (when-let* ((node-at-point (tree-sitter-node-at-point))
              (current-type (tsc-node-type node-at-point))
              (parent (tsc-get-parent node-at-point))
              (parent-type (tsc-node-type parent)))
```

`when-let*` will stop if any binding is `nil`. If `tree-sitter-node-at-point` returned `void` instead of `nil` in certain setups (no native complication?) we would see this error.

I guess the first step though is to try to find a way to reliably reproduce. I've only tested with Emacs 28.* with native compilation so far.

**Comment by pavel-blagodov** [comment]
Hi @stevemolitor,
I'm receiving the same error. Here is stack trace

```
Debugger entered--Lisp error: (void-variable node-at-point)
  tsi-typescript--get-indent-for-current-line()
  tsi-indent-line(tsi-typescript--get-indent-for tsi-typescript--get-indent-for-current-line)
  tsi-typescript--indent-line()
  indent--funcall-widened(tsi-typescript--indent-line)
  indent-for-tab-command(nil)
  funcall-interactively(indent-for-tab-command nil)
  call-interactively(indent-for-tab-command nil nil)
  command-execute(indent-for-tab-command)
```

**Comment by pavel-blagodov** [comment]
I did all the above actions on clearing cache and rebuilding. I'm still receiving the same error. Disabling of  tsi-typescript-mode  and retrigger of typescript-mode does help. I use emacs 28.1(9.0) MacOS Monterey.

**Comment by pavel-blagodov** [comment]
Also, I see the following in Compile-log
Warning (bytecomp): the function ‘web-mode-part-args-beginning’ is not known to be defined.
After that, I was offered to select alternatives:
jsts-ls
ts-ls
eslint

**Comment by carlosecp** [comment]
I'm having the same issue here but using Doom, should I send my `config.el` file to test this?

**Comment by orzechowskid** [comment]
> I'm having the same issue here but using Doom, should I send my `config.el` file to test this?

that would be great.  please also include the version of Emacs you are using.  thanks!

**Comment by orzechowskid** [comment]
ok, I've finally been able to reproduce this with emacs 28 (I usually run snapshot, which has been emacs 29 for a while now).  I'm still not sure why that `when-let*` is causing so much trouble, but I cleaned up the variables a little and things seem to function correctly.  (tests currently don't pass, but I believe that's due to a different issue).

I've pushed an update to mainline; please check it out if you've encountered this problem and let me know if things work for you now.  thanks!

**Comment by furious-luke** [comment]
Yep, that's solved it for me. This is great, the indentation is working just as I would expect now. Thanks so much @orzechowskid!

**Comment by orzechowskid** [comment]
great!
